package wrappers.opengl

import org.lwjgl.opengl.GL45.*

enum class FramebufferParameter(val native: Int) {
    DEFAULT_WIDTH(GL_FRAMEBUFFER_DEFAULT_WIDTH),
    DEFAULT_HEIGHT(GL_FRAMEBUFFER_DEFAULT_HEIGHT),
    DEFAULT_LAYERS(GL_FRAMEBUFFER_DEFAULT_LAYERS),
    DEFAULT_SAMPLES(GL_FRAMEBUFFER_DEFAULT_SAMPLES),
    DEFAULT_FIXED_SAMPLE_LOCATIONS(GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS),
    DOUBLEBUFFER(GL_DOUBLEBUFFER),
    IMPLEMENTATION_COLOR_READ_FORMAT(GL_IMPLEMENTATION_COLOR_READ_FORMAT),
    IMPLEMENTATION_COLOR_READ_TYPE(GL_IMPLEMENTATION_COLOR_READ_TYPE),
    SAMPLES(GL_SAMPLES),
    SAMPLE_BUFFERS(GL_SAMPLE_BUFFERS),
    STEREO(GL_STEREO),
}