package wrappers.opengl

import org.lwjgl.opengl.GL45.*

enum class PipelineParameter(val native: Int) {
    ACTIVE_PROGRAM(GL_ACTIVE_PROGRAM),
    VERTEX_SHADER(GL_VERTEX_SHADER),
    TESS_CONTROL_SHADER(GL_TESS_CONTROL_SHADER),
    TESS_EVALUATION_SHADER(GL_TESS_EVALUATION_SHADER),
    GEOMETRY_SHADER(GL_GEOMETRY_SHADER),
    FRAGMENT_SHADER(GL_FRAGMENT_SHADER),
    INFO_LOG_LENGTH(GL_INFO_LOG_LENGTH),
}