package wrappers.opengl

import org.lwjgl.opengl.GL45.*

enum class ProgramParameter(val native: Int) {
    DELETE_STATUS(GL_DELETE_STATUS),
    LINK_STATUS(GL_LINK_STATUS),
    VALIDATE_STATUS(GL_VALIDATE_STATUS),
    INFO_LOG_LENGTH(GL_INFO_LOG_LENGTH),
    ATTACHED_SHADERS(GL_ATTACHED_SHADERS),
    ACTIVE_ATOMIC_COUNTER_BUFFERS(GL_ACTIVE_ATOMIC_COUNTER_BUFFERS),
    ACTIVE_ATTRIBUTES(GL_ACTIVE_ATTRIBUTES),
    ACTIVE_ATTRIBUTE_MAX_LENGTH(GL_ACTIVE_ATTRIBUTE_MAX_LENGTH),
    ACTIVE_UNIFORMS(GL_ACTIVE_UNIFORMS),
    ACTIVE_UNIFORM_MAX_LENGTH(GL_ACTIVE_UNIFORM_MAX_LENGTH),
    PROGRAM_BINARY_LENGTH(GL_PROGRAM_BINARY_LENGTH),
    COMPUTE_WORK_GROUP_SIZE(GL_COMPUTE_WORK_GROUP_SIZE),
    TRANSFORM_FEEDBACK_BUFFER_MODE(GL_TRANSFORM_FEEDBACK_BUFFER_MODE),
    TRANSFORM_FEEDBACK_VARYINGS(GL_TRANSFORM_FEEDBACK_VARYINGS),
    TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH(GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH),
    GEOMETRY_VERTICES_OUT(GL_GEOMETRY_VERTICES_OUT),
    GEOMETRY_INPUT_TYPE(GL_GEOMETRY_INPUT_TYPE),
    GEOMETRY_OUTPUT_TYPE(GL_GEOMETRY_OUTPUT_TYPE),
}