package wrappers.opengl

import org.lwjgl.opengl.GL45.*

enum class TextureLevelParameter(val native: Int) {
    WIDTH(GL_TEXTURE_WIDTH),
    HEIGHT(GL_TEXTURE_HEIGHT),
    DEPTH(GL_TEXTURE_DEPTH),
    INTERNAL_FORMAT(GL_TEXTURE_INTERNAL_FORMAT),
    RED_TYPE(GL_TEXTURE_RED_TYPE),
    GREEN_TYPE(GL_TEXTURE_GREEN_TYPE),
    BLUE_TYPE(GL_TEXTURE_BLUE_TYPE),
    ALPHA_TYPE(GL_TEXTURE_ALPHA_TYPE),
    DEPTH_TYPE(GL_TEXTURE_DEPTH_TYPE),
    RED_SIZE(GL_TEXTURE_RED_SIZE),
    GREEN_SIZE(GL_TEXTURE_GREEN_SIZE),
    BLUE_SIZE(GL_TEXTURE_BLUE_SIZE),
    ALPHA_SIZE(GL_TEXTURE_ALPHA_SIZE),
    DEPTH_SIZE(GL_TEXTURE_DEPTH_SIZE),
    COMPRESSED(GL_TEXTURE_COMPRESSED),
    COMPRESSED_IMAGE_SIZE(GL_TEXTURE_COMPRESSED_IMAGE_SIZE),
    BUFFER_OFFSET(GL_TEXTURE_BUFFER_OFFSET),
    BUFFER_SIZE(GL_TEXTURE_BUFFER_SIZE),
}