package wrappers.opengl

import org.lwjgl.opengl.GL45.*

enum class TextureParameter(val native: Int) {
    DEPTH_STENCIL_TEXTURE_MODE(GL_DEPTH_STENCIL_TEXTURE_MODE),
    MAG_FILTER(GL_TEXTURE_MAG_FILTER),
    MIN_FILTER(GL_TEXTURE_MIN_FILTER),
    MIN_LOD(GL_TEXTURE_MIN_LOD),
    MAX_LOD(GL_TEXTURE_MAX_LOD),
    BASE_LEVEL(GL_TEXTURE_BASE_LEVEL),
    MAX_LEVEL(GL_TEXTURE_MAX_LEVEL),
    SWIZZLE_R(GL_TEXTURE_SWIZZLE_R),
    SWIZZLE_G(GL_TEXTURE_SWIZZLE_G),
    SWIZZLE_B(GL_TEXTURE_SWIZZLE_B),
    SWIZZLE_A(GL_TEXTURE_SWIZZLE_A),
    SWIZZLE_RGBA(GL_TEXTURE_SWIZZLE_RGBA),
    WRAP_S(GL_TEXTURE_WRAP_S),
    WRAP_T(GL_TEXTURE_WRAP_T),
    WRAP_R(GL_TEXTURE_WRAP_R),
    BORDER_COLOR(GL_TEXTURE_BORDER_COLOR),
    COMPARE_MODE(GL_TEXTURE_COMPARE_MODE),
    COMPARE_FUNC(GL_TEXTURE_COMPARE_FUNC),
    VIEW_MIN_LEVEL(GL_TEXTURE_VIEW_MIN_LEVEL),
    VIEW_NUM_LEVELS(GL_TEXTURE_VIEW_NUM_LEVELS),
    VIEW_MIN_LAYER(GL_TEXTURE_VIEW_MIN_LAYER),
    VIEW_NUM_LAYERS(GL_TEXTURE_VIEW_NUM_LAYERS),
    IMMUTABLE_LEVELS(GL_TEXTURE_IMMUTABLE_LEVELS),
    IMAGE_FORMAT_COMPATIBILITY_TYPE(GL_IMAGE_FORMAT_COMPATIBILITY_TYPE),
    IMMUTABLE_FORMAT(GL_TEXTURE_IMMUTABLE_FORMAT),
    TARGET(GL_TEXTURE_TARGET),
}